var categories = (browser, number, category) => {
    browser
    .useXpath()
        .click('(//div[text()="See all"])[' + number + ']')
        .waitForElementVisible('//div[text()="category: ' + category + '"]', 10000)
        .url('https://alpha.yoodlize.com/')
    .useCss
}

module.exports = {
    beforeEach: browser => {
        browser.url('https://alpha.yoodlize.com/')
    },
    after: browser => {
        browser.end()
    },
    'Navigate Categories': browser => {
       categories(browser, '1', 'Tools')
    //     .click('(//div[text()="See all"])[2]')
    //     .waitForElementVisible('//div[text()="category: Outdoor Gear"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[3]')
    //     .waitForElementVisible('//div[text()="category: Electronics"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[4]')
    //     .waitForElementVisible('//div[text()="category: Party Equipment"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[5]')
    //     .waitForElementVisible('//div[text()="category: Recreational Vehicles"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[6]')
    //     .waitForElementVisible('//div[text()="category: Clothing"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[7]')
    //     .waitForElementVisible('//div[text()="category: Home and Kitchen"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[8]')
    //     .waitForElementVisible('//div[text()="category: Toys and Games"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[9]')
    //     .waitForElementVisible('//div[text()="category: Lawn and Garden"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[10]')
    //     .waitForElementVisible('//div[text()="category: Sporting Goods"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[11]')
    //     .waitForElementVisible('//div[text()="category: Business Equipment"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[12]')
    //     .waitForElementVisible('//div[text()="category: Venues"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[13]')
    //     .waitForElementVisible('//div[text()="category: Local Experts"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[14]')
    //     .waitForElementVisible('//div[text()="category: Experiences"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="See all"])[15]')
    //     .waitForElementVisible('//div[text()="category: Misc"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
       
    //     .click('(//div[text()="TOOLS"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Tools"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="OUTDOOR GEAR"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Outdoor Gear"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="ELECTRONICS"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Electronics"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="PARTY EQUIPMENT"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Party Equipment"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="RECREATIONAL VEHICLES"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Recreational Vehicles"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="CLOTHING"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Clothing"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="HOME AND KITCHEN"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Home and Kitchen"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="TOYS AND GAMES"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Toys and Games"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="LAWN AND GARDEN"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Lawn and Garden"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="SPORTING GOODS"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Sporting Goods"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="BUSINESS EQUIPMENT"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Business Equipment"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="VENUES"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Venues"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="LOCAL EXPERTS"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Local Experts"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="EXPERIENCES"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Experiences"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    //     .click('(//div[text()="MISC"])[last()]')
    //     .waitForElementVisible('//div[text()="category: Misc"]', 10000)
    //     .url('https://alpha.yoodlize.com/') 
    // },
    // 'Search for an Item': browser => {
    //     browser
    //     .setValue('.form-control', ['Rubix Cube', browser.Keys.ENTER])
    // .useXpath()
    //     .waitForElementVisible('//div[text()="keyword: "and"Rubix Cube"]', 10000)
    //     .waitForElementVisible('(//div[text()="Rubix Cube"])[2]', 10000)
    //     .waitForElementVisible('//span[text()="$22"]', 10000)
    // .useCss()
    //     .waitForElementVisible('[value="Rubix Cube"]')
    //     .waitForElementVisible('[style="height: 100%;"]')
    }

}