var yoopg
module.exports = {
    beforeEach: browser => {
        yoopg = browser.page.yoodlize()
        yoopg.navigate()
    },
    after: browser => {
        browser.end()
    },
    'Navigate Categories': browser => {
        yoopg
    .api.useXpath()
        yoopg
        .click('(//div[text()="See all"])[1]')
        .waitForElementVisible('@tl', 10000)
        yoopg.navigate()
    yoopg 
        .click('(//div[text()="See all"])[2]')
        .waitForElementVisible('@og', 10000)
        .navigate()
        .click('(//div[text()="See all"])[3]')
        .waitForElementVisible('@el', 10000)
        .navigate()
        .click('(//div[text()="See all"])[4]')
        .waitForElementVisible('@pe', 10000)
        .navigate()
        .click('(//div[text()="See all"])[5]')
        .waitForElementVisible('@rv', 10000)
        .navigate()
        .click('(//div[text()="See all"])[6]')
        .waitForElementVisible('@cl', 10000)
        .navigate()
        .click('(//div[text()="See all"])[7]')
        .waitForElementVisible('@hk', 10000)
        .navigate()
        .click('(//div[text()="See all"])[8]')
        .waitForElementVisible('@tg', 10000)
        .navigate()
        .click('(//div[text()="See all"])[9]')
        .waitForElementVisible('@lg', 10000)
        .navigate()
        .click('(//div[text()="See all"])[10]')
        .waitForElementVisible('@sg', 10000)
        .navigate()
        .click('(//div[text()="See all"])[11]')
        .waitForElementVisible('@be', 10000)
        .navigate()
        .click('(//div[text()="See all"])[12]')
        .waitForElementVisible('@vs', 10000)
        .navigate()
        .click('(//div[text()="See all"])[13]')
        .waitForElementVisible('@le', 10000)
        .navigate()
        .click('(//div[text()="See all"])[14]')
        .waitForElementVisible('@ex', 10000)
        .navigate()
        .click('(//div[text()="See all"])[15]')
        .waitForElementVisible('@mi', 10000)
        .navigate()
       
        .click('(//div[text()="TOOLS"])[last()]')
        .waitForElementVisible('@tl', 10000)
        .navigate()
        .click('(//div[text()="OUTDOOR GEAR"])[last()]')
        .waitForElementVisible('@og', 10000)
        .navigate()
        .click('(//div[text()="ELECTRONICS"])[last()]')
        .waitForElementVisible('@el', 10000)
        .navigate()
        .click('(//div[text()="PARTY & WEDDING EQUIPMENT"])[last()]')
        .waitForElementVisible('@pe', 10000)
        .navigate()
        .click('(//div[text()="RECREATIONAL VEHICLES"])[last()]')
        .waitForElementVisible('@rv', 10000)
        .navigate()
        .click('(//div[text()="CLOTHING"])[last()]')
        .waitForElementVisible('@cl', 10000)
        .navigate()
        .click('(//div[text()="HOME AND KITCHEN"])[last()]')
        .waitForElementVisible('@hk', 10000)
        .navigate()
        .click('(//div[text()="TOYS AND GAMES"])[last()]')
        .waitForElementVisible('@tg', 10000)
        .navigate()
        .click('(//div[text()="LAWN AND GARDEN"])[last()]')
        .waitForElementVisible('@lg', 10000)
        .navigate()
        .click('(//div[text()="SPORTING GOODS"])[last()]')
        .waitForElementVisible('@sg', 10000)
        .navigate()
        .click('(//div[text()="BUSINESS EQUIPMENT"])[last()]')
        .waitForElementVisible('@be', 10000)
        .navigate()
        .click('(//div[text()="VENUES"])[last()]')
        .waitForElementVisible('@vs', 10000)
        .navigate()
        .click('(//div[text()="LOCAL EXPERTS"])[last()]')
        .waitForElementVisible('@le', 10000)
        .navigate()
        .click('(//div[text()="EXPERIENCES"])[last()]')
        .waitForElementVisible('@ex', 10000)
        .navigate()
        .click('(//div[text()="MISC"])[last()]')
        .waitForElementVisible('@mi', 10000)
        .navigate()
    },
    // 'Search for an Item': browser => {
    //     browser
    //     .setValue('.form-control', ['Rubix Cube', browser.Keys.ENTER])
    // .useXpath()
    //     .waitForElementVisible('//div[text()="keyword: "and"Rubix Cube"]', 10000)
    //     .waitForElementVisible('(//div[text()="Rubix Cube"])[2]', 10000)
    //     .waitForElementVisible('//span[text()="$22"]', 10000)
    // .useCss()
    //     .waitForElementVisible('[value="Rubix Cube"]')
    //     .waitForElementVisible('[style="height: 100%;"]')
    // }
}